[project]
name = "fake-excel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faker>=36.2.2",
    "pyexcel>=0.7.1",
    "pyexcel-xlsx>=0.6.1",
]
